spring.application.name=zeroknowledge-vault
server.port=8080

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-sparkling-cherry-acpvwqud-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_V8T6QyBUcpnP
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE (JPA)
# ===============================
# update: Crea/actualiza las tablas automáticamente basándose en nuestras clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
